using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Turniejowo.API.Models;

namespace Turniejowo.API.Services
{
    public interface IMatchService
    {
        Task<ICollection<Match>> GetAllMatchesAsync();

        Task<Match> GetMatchByIdAsync(int id);

        Task<ICollection<Points>> GetPointsForMatch(int matchId);

        Task AddNewMatchAsync(Match match,bool autoGenerated = false);

        Task EditMatchAsync(Match match);

        Task DeleteMatchAsync(int id);

        Task DeleteMatchesRelatedToTheTeamAsync(int id);
    }
}
