using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Turniejowo.API.Exceptions;
using Turniejowo.API.Models;
using Turniejowo.API.Repositories;
using Turniejowo.API.UnitOfWork;

namespace Turniejowo.API.Services
{
    public class MatchService : IMatchService
    {
        private readonly IMatchRepository matchRepository;
        private readonly ITeamRepository teamRepository;
        private readonly IPointsRepository pointsRepository;
        private readonly ITournamentRepository tournamentRepository;
        private readonly IUnitOfWork unitOfWork;

        public MatchService(IMatchRepository matchRepository, ITeamRepository teamRepository, IPointsRepository pointsRepository, IUnitOfWork unitOfWork, ITournamentRepository tournamentRepository)
        {
            this.matchRepository = matchRepository;
            this.teamRepository = teamRepository;
            this.pointsRepository = pointsRepository;
            this.unitOfWork = unitOfWork;
            this.tournamentRepository = tournamentRepository;
        }

        public async Task<ICollection<Match>> GetAllMatchesAsync()
        {
            var matches = await matchRepository.GetAllAsync(new string[]{"HomeTeam","GuestTeam"});

            if (matches.Count == 0)
            {
                throw new NotFoundInDatabaseException();
            }

            return matches;
        }

        public async Task<Match> GetMatchByIdAsync(int id)
        {
            var match = await matchRepository.FindSingleAsync(m => m.MatchId == id,new string[]{"HomeTeam","GuestTeam"})
                        ?? throw new NotFoundInDatabaseException();

            if (match == null)
            {
                throw new NotFoundInDatabaseException();
            }

            return match;
        }

        public async Task<ICollection<Points>> GetPointsForMatch(int matchId)
        {
            var match = await matchRepository.FindSingleAsync(m => m.MatchId == matchId)
                        ?? throw new NotFoundInDatabaseException();

            var points = await pointsRepository.FindAsync(p => p.MatchId == matchId, new string[] { "Tournament", "Player", "Match" });

            return points;
        }

        public async Task AddNewMatchAsync(Match match, bool autoGenerated = false)
        {
            var teamA = await teamRepository.FindSingleAsync(x => x.TeamId == match.HomeTeamId);
            var teamB = await teamRepository.FindSingleAsync(y => y.TeamId == match.GuestTeamId);

            if (teamA == null ||
                teamB == null)
            {
                throw new NotFoundInDatabaseException();
            }

            var matches = await matchRepository.FindAsync(m => m.MatchDateTime == match.MatchDateTime);

            var isAnyTeamAlreadyPlaying = matches.Select(y => new[] {y.HomeTeamId, y.GuestTeamId}).Any(o => o.Contains(match.HomeTeamId) || o.Contains(match.GuestTeamId));

            if (isAnyTeamAlreadyPlaying)
            {
                throw new AlreadyInDatabaseException();
            }

            if (teamA.TournamentId != teamB.TournamentId)
            {
                throw new ArgumentException();
            }

            var tournament = await tournamentRepository.FindSingleAsync(t => t.TournamentId == teamA.TournamentId);

            if (tournament.IsBracket)
            {
                var matchesBracket =
                    await matchRepository.FindAsync(m =>
                        m.HomeTeam.TournamentId == tournament.TournamentId &&
                        m.GuestTeam.TournamentId == tournament.TournamentId);

                if (matchesBracket.Count(m => m.BracketIndex <= tournament.AmountOfTeams / 2) == tournament.AmountOfTeams / 2 && !autoGenerated)
                {
                    throw new ArgumentOutOfRangeException();
                }

                int bracketIndexForMatch = FindFirstEmptyBracketSlot(matchesBracket, tournament.AmountOfTeams);
                match.BracketIndex = bracketIndexForMatch;
            }

            matchRepository.Add(match);
            await unitOfWork.CompleteAsync();
        }

        public async Task EditMatchAsync(Match match)
        {
            var matchToEdit = await matchRepository.FindSingleAsync(x => x.MatchId == match.MatchId) ?? throw new NotFoundInDatabaseException(); ;

            if (await teamRepository.FindSingleAsync(x => x.TeamId == match.HomeTeamId) == null || await teamRepository.FindSingleAsync(y => y.TeamId == match.GuestTeamId) == null)
            {
                throw new NotFoundInDatabaseException();
            }

            matchRepository.ClearEntryState(matchToEdit);

            matchRepository.Update(match);
            await unitOfWork.CompleteAsync();
        }

        public async Task DeleteMatchAsync(int id)
        {
            var matchToDel = await matchRepository.FindSingleAsync(x => x.MatchId == id) ?? throw new NotFoundInDatabaseException();

            matchRepository.Delete(matchToDel);
            await unitOfWork.CompleteAsync();
        }

        public async Task DeleteMatchesRelatedToTheTeamAsync(int id)
        {
            var matches = await matchRepository.FindAsync(m => m.GuestTeamId == id || m.HomeTeamId == id);

            foreach (var match in matches)
            {
                await DeleteMatchAsync(match.MatchId);
            }

            await unitOfWork.CompleteAsync();
        }

        private int FindFirstEmptyBracketSlot(ICollection<Match> matches, int teamsQty)
        {
            for (int i = 1; i < teamsQty; i++)
            {
                if (matches.FirstOrDefault(m => m.BracketIndex == i) == null)
                {
                    return i;
                }
            }

            throw new ArgumentOutOfRangeException();
        }
    }
}
